#!/usr/bin/env python3
"""Sync curriculum.md implementation-status markers from the source of truth.

Reads:
  - lib/domain/questions/generator_registry.dart  -> implemented sub-concept IDs
  - lib/presentation/diagrams/                    -> implemented diagram-widget files
  - assets/data/                                  -> integrated dataset files

Writes (idempotently) into curriculum.md:
  - top Status block: rolled-up counts inside <!-- IMPL_STATUS --> fences
  - §3.x tables: leading "| ✅ " on rows whose concept ID is in the registry
  - §6.1 / §6.2 tables: leading "| ✅ " on rows whose widget file exists
  - §7.2 datasets: "Integrated to date" line inside <!-- DATASET_STATUS --> fences

Idempotent: running twice produces no further changes. Safe to run repeatedly.

Usage (from repo root):
    python3 tools/curriculum/sync_implementation_status.py

Run this whenever you add or remove:
  - an entry in generator_registry.dart
  - a file in lib/presentation/diagrams/
  - a dataset in assets/data/
"""

from __future__ import annotations

import datetime
import os
import re
import sys

REPO = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
REGISTRY = os.path.join(REPO, "lib/domain/questions/generator_registry.dart")
DIAGRAMS_DIR = os.path.join(REPO, "lib/presentation/diagrams")
DATA_DIR = os.path.join(REPO, "assets/data")
CURRICULUM = os.path.join(REPO, "curriculum.md")

# Map widget identifier (the leading `Name(...)` in §6.x tables) to its expected
# .dart filename stem under lib/presentation/diagrams/. Update this dict when a
# new widget is catalogued in §6 OR when a file is added under a non-obvious name
# (e.g. `RectangleArea` is implemented as `area_grid.dart`).
WIDGET_TO_FILE = {
    # §6.1 — 8-widget unlock set
    "FractionBar": "fraction_bar",
    "NumberLine": "number_line",
    "Clock": "clock",
    "BarChart": "bar_chart",
    # BarChart and Histogram share §6.1 row 1; DotPlot and LinePlot share
    # §6.1 row 2 (split landed in Chunk 28). Map the secondary widgets to
    # their files so the impl-vs-catalogued cross-check passes.
    "Histogram": "histogram",
    "DotPlot": "dot_plot",
    "RectangleArea": "area_grid",  # implemented under this name historically
    "CoordinatePlane": "coordinate_plane",
    "Angle": "angle",
    # TriangleAngles is paired with Angle in the §6.1 row (separate Spec, same
    # row in curriculum.md). Mapped here so the impl-vs-catalogued cross-check
    # passes.
    "TriangleAngles": "triangle_angles",
    "PictureGraph": "picture_graph",
    "Spinner": "spinner",
    # §6.2 — second-tier
    "BaseTenBlocks": "base_ten_blocks",
    "Polygon": "polygon",
    "Shape": "shape",
    "TapeDiagram": "tape_diagram",
    "DoubleNumberLine": "double_number_line",
    "Box3D": "box_3d",
    "Circle": "circle",
    "Protractor": "protractor",
    "Ruler": "ruler",
    "Money": "money",  # widget file already in §6.2 row 10
    "BoxPlot": "box_plot",
    "ScatterPlot": "scatter_plot",
    "TwoWayTable": "two_way_table",
    "TreeDiagram": "tree_diagram",
    "Net3D": "net_3d",
    "ColumnArithmetic": "column_arithmetic",
    "PercentGrid": "percent_grid",
}

# Total datasets tracked in §7.2.
DATASET_TOTAL = 5

IMPL_BEGIN = "<!-- IMPL_STATUS_BEGIN (auto-generated by tools/curriculum/sync_implementation_status.py) -->"
IMPL_END = "<!-- IMPL_STATUS_END -->"
DATASET_BEGIN = "<!-- DATASET_STATUS_BEGIN (auto-generated by tools/curriculum/sync_implementation_status.py) -->"
DATASET_END = "<!-- DATASET_STATUS_END -->"


def read_implemented_generators() -> set[str]:
    """Extract sub-concept IDs registered in generator_registry.dart."""
    with open(REGISTRY) as f:
        text = f.read()
    # Keep matches only within the _buildDefault() map body to avoid picking up
    # unrelated string keys elsewhere in the file.
    m = re.search(r"_buildDefault\(\)\s*=>\s*\{(.+?)\n\s*\};", text, re.DOTALL)
    body = m.group(1) if m else text
    return set(re.findall(r"'([a-z0-9_]+)'\s*:", body))


def read_implemented_widget_files() -> set[str]:
    if not os.path.isdir(DIAGRAMS_DIR):
        return set()
    stems = {f[:-5] for f in os.listdir(DIAGRAMS_DIR) if f.endswith(".dart")}
    # The dispatcher is not a widget, just the renderer that delegates to widgets.
    stems.discard("diagram_renderer")
    return stems


def count_integrated_datasets() -> int:
    if not os.path.isdir(DATA_DIR):
        return 0
    return sum(1 for e in os.listdir(DATA_DIR) if not e.startswith("."))


# ---- curriculum.md transforms ----------------------------------------------


CONCEPT_ROW_RE = re.compile(r"^\| (✅ )?`([a-z0-9_]+)` \|")
WIDGET_ROW_RE = re.compile(r"^\| (✅ )?`([A-Z][A-Za-z0-9]+)\(")


def toggle_concept_row(line: str, implemented: set[str]):
    m = CONCEPT_ROW_RE.match(line)
    if not m:
        return line, None
    is_marked = m.group(1) is not None
    cid = m.group(2)
    should_be_marked = cid in implemented
    if is_marked == should_be_marked:
        return line, ("unchanged", cid)
    if should_be_marked:
        return line.replace(f"| `{cid}` |", f"| ✅ `{cid}` |", 1), ("added", cid)
    return line.replace(f"| ✅ `{cid}` |", f"| `{cid}` |", 1), ("removed", cid)


def toggle_widget_row(line: str, implemented_files: set[str]):
    m = WIDGET_ROW_RE.match(line)
    if not m:
        return line, None
    is_marked = m.group(1) is not None
    widget = m.group(2)
    expected = WIDGET_TO_FILE.get(widget)
    should_be_marked = expected is not None and expected in implemented_files
    if is_marked == should_be_marked:
        return line, ("unchanged", widget)
    if should_be_marked:
        return re.sub(r"^\| `", "| ✅ `", line, count=1), ("added", widget)
    return re.sub(r"^\| ✅ `", "| `", line, count=1), ("removed", widget)


def replace_or_insert_fenced_block(
    text: str, begin: str, end: str, body: str, anchor_pattern: str
) -> str:
    """Replace content between fence markers, or insert a new fenced block.

    If the fences exist anywhere, replace their content (and the fences too — we
    rewrite the whole block to keep the begin-comment's `auto-generated` hint
    fresh). Otherwise, insert the block right after the first line matching
    `anchor_pattern` (a regex).
    """
    new_block = f"{begin}\n{body}\n{end}"
    if begin.split(" (auto")[0] in text or end in text:
        # Use a tolerant regex for the begin marker since older runs may have
        # written a slightly different "auto-generated by ..." line.
        begin_re = re.compile(r"<!-- IMPL_STATUS_BEGIN[^>]*-->") if "IMPL_STATUS" in begin else re.compile(r"<!-- DATASET_STATUS_BEGIN[^>]*-->")
        end_re = re.compile(re.escape(end))
        return re.sub(
            rf"{begin_re.pattern}.*?{end_re.pattern}",
            new_block.replace("\\", "\\\\"),  # escape backslashes for re.sub
            text,
            count=1,
            flags=re.DOTALL,
        )
    # Insert just after the anchor line.
    anchor_re = re.compile(anchor_pattern, re.MULTILINE)
    m = anchor_re.search(text)
    if not m:
        # No anchor — append at end as a fallback.
        return text.rstrip() + "\n\n" + new_block + "\n"
    insert_at = m.end()
    return text[:insert_at] + "\n\n" + new_block + text[insert_at:]


def update_status_block(text: str, n_concepts_total: int, n_concepts_done: int,
                        n_widgets_total: int, n_widgets_done: int,
                        n_datasets_total: int, n_datasets_done: int,
                        today: str) -> str:
    pct = (n_concepts_done / n_concepts_total * 100) if n_concepts_total else 0.0
    body = (
        f"- **Implementation status (auto-updated {today}):**\n"
        f"  - Sub-concepts: **{n_concepts_done} / {n_concepts_total} implemented** ({pct:.0f}%) — see ✅ marks in §3 tables. Source of truth: [generator_registry.dart](lib/domain/questions/generator_registry.dart).\n"
        f"  - Diagram widgets: **{n_widgets_done} / {n_widgets_total} implemented** — see ✅ marks in §6 tables. Source of truth: [lib/presentation/diagrams/](lib/presentation/diagrams/).\n"
        f"  - Datasets: **{n_datasets_done} / {n_datasets_total} integrated** — see §7.2. Source of truth: [assets/data/](assets/data/).\n"
        f"  - To refresh these counts and the per-row ✅ marks, run `python3 tools/curriculum/sync_implementation_status.py`."
    )
    return replace_or_insert_fenced_block(
        text,
        IMPL_BEGIN,
        IMPL_END,
        body,
        # Anchor after the "Categories: 12" line of the Status block.
        anchor_pattern=r"^- \*\*Categories:\*\* .*$",
    )


def update_dataset_block(text: str, n_done: int, n_total: int) -> str:
    if n_done == 0:
        body = (
            f"**Integrated to date:** 0 / {n_total}. The dataset ingestion sub-track has not started — "
            f"see the [Phase 6 dataset sub-track in plan.md](plan.md). Generators-first means we extend "
            f"algorithmic coverage before ingesting bundled datasets."
        )
    else:
        body = f"**Integrated to date:** {n_done} / {n_total}. See [assets/data/](assets/data/) for the bundled JSON."
    return replace_or_insert_fenced_block(
        text,
        DATASET_BEGIN,
        DATASET_END,
        body,
        # Anchor after the §7.2 heading line.
        anchor_pattern=r"^### 7\.2 Top 5 datasets to ingest$",
    )


def main() -> int:
    impl_concepts = read_implemented_generators()
    impl_widget_files = read_implemented_widget_files()
    n_datasets = count_integrated_datasets()
    today = datetime.date.today().isoformat()

    with open(CURRICULUM) as f:
        lines = f.readlines()

    added = removed = 0
    found_ids: set[str] = set()
    found_widgets: set[str] = set()
    out_lines = []
    for line in lines:
        new_line, info = toggle_concept_row(line, impl_concepts)
        if info is not None:
            action, cid = info
            found_ids.add(cid)
            if action == "added":
                added += 1
            elif action == "removed":
                removed += 1
            out_lines.append(new_line)
            continue
        new_line, info = toggle_widget_row(line, impl_widget_files)
        if info is not None:
            action, w = info
            found_widgets.add(w)
            if action == "added":
                added += 1
            elif action == "removed":
                removed += 1
        out_lines.append(new_line)

    text = "".join(out_lines)

    # Count totals from the document itself so the rollup matches what we just
    # walked (avoids drift between "what's in the catalog" and "what we know about").
    n_concepts_total = sum(1 for line in out_lines if CONCEPT_ROW_RE.match(line))
    n_widgets_total = sum(1 for line in out_lines if WIDGET_ROW_RE.match(line))
    n_concepts_done = sum(
        1 for line in out_lines if (m := CONCEPT_ROW_RE.match(line)) and m.group(1)
    )
    n_widgets_done = sum(
        1 for line in out_lines if (m := WIDGET_ROW_RE.match(line)) and m.group(1)
    )

    text = update_status_block(
        text,
        n_concepts_total, n_concepts_done,
        n_widgets_total, n_widgets_done,
        DATASET_TOTAL, n_datasets,
        today,
    )
    text = update_dataset_block(text, n_datasets, DATASET_TOTAL)

    with open(CURRICULUM, "w") as f:
        f.write(text)

    print(f"sub-concepts: {n_concepts_done} / {n_concepts_total} implemented")
    print(f"widgets:      {n_widgets_done} / {n_widgets_total} implemented")
    print(f"datasets:     {n_datasets} / {DATASET_TOTAL} integrated")
    print(f"markers:      +{added} added, -{removed} removed")

    # Audit: implemented IDs not present anywhere in curriculum.md = name drift.
    missing_ids = impl_concepts - found_ids
    if missing_ids:
        print(
            f"\nWARNING: {len(missing_ids)} concept IDs are in the registry but "
            f"not in curriculum.md (rename/typo?):"
        )
        for cid in sorted(missing_ids):
            print(f"  - {cid}")

    # Audit: widget files that don't correspond to any catalogued widget.
    catalogued_files = set(WIDGET_TO_FILE.values())
    orphan_widget_files = impl_widget_files - catalogued_files
    if orphan_widget_files:
        print(
            f"\nWARNING: widget files exist that are not in WIDGET_TO_FILE — add "
            f"them to the dict in this script AND to §6 of curriculum.md:"
        )
        for stem in sorted(orphan_widget_files):
            print(f"  - lib/presentation/diagrams/{stem}.dart")

    # Audit: WIDGET_TO_FILE entries whose file exists but no §6 row was found.
    # This catches the case where a widget is implemented + mapped here but the
    # curriculum.md catalog never got a row for it.
    mapped_implemented = {
        w for w, stem in WIDGET_TO_FILE.items() if stem in impl_widget_files
    }
    uncatalogued = mapped_implemented - found_widgets
    if uncatalogued:
        print(
            f"\nWARNING: these widgets are implemented and in WIDGET_TO_FILE, but "
            f"§6 of curriculum.md has no row for them — add a row so the marker "
            f"can be applied:"
        )
        for w in sorted(uncatalogued):
            print(f"  - {w}  (file: lib/presentation/diagrams/{WIDGET_TO_FILE[w]}.dart)")

    return 0


if __name__ == "__main__":
    sys.exit(main())
