#!/usr/bin/env python3
"""Sync city_builder.md implementation-status markers from the source of truth.

Reads:
  - lib/domain/city/building_registry.dart -> wired building IDs + numVariants
  - lib/domain/city/beat_registry.dart     -> wired story-beat IDs
  - assets/buildings/                      -> processed sprite variants per ID

Writes (idempotently) into city_builder.md:
  - §3.1–§3.4 tables: leading "| ✅ " on rows whose building ID is in
    building_registry.dart
  - §4.x tables: leading "| ✅ " on rows whose beat ID is in beat_registry.dart
  - §6: rolled-up counts inside <!-- IMPL_STATUS --> fences

Idempotent: running twice produces no further changes. Safe to run repeatedly.

Usage (from repo root):
    python3 tools/city_builder/sync_implementation_status.py

Run this whenever you add or remove:
  - an entry in building_registry.dart or beat_registry.dart
  - a processed sprite under assets/buildings/

Mirrors tools/curriculum/sync_implementation_status.py (same conventions).
"""

from __future__ import annotations

import datetime
import os
import re
import sys

REPO = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
BUILDING_REGISTRY = os.path.join(REPO, "lib/domain/city/building_registry.dart")
BEAT_REGISTRY = os.path.join(REPO, "lib/domain/city/beat_registry.dart")
ASSETS_DIR = os.path.join(REPO, "assets/buildings")
CITY_BUILDER = os.path.join(REPO, "city_builder.md")

IMPL_BEGIN = "<!-- IMPL_STATUS_BEGIN (auto-generated by tools/city_builder/sync_implementation_status.py) -->"
IMPL_END = "<!-- IMPL_STATUS_END -->"

# Sprite assets are <id>_v<n>.png; anything else under assets/buildings/
# (road tiles, future terrain) is not building art.
ASSET_RE = re.compile(r"^([a-z0-9_]+)_v(\d+)\.png$")

# A §3 / §4 table row: optional ✅, then the backticked ID. The emoji and any
# legacy ✓P7 origin marker that follow stay untouched.
ROW_RE = re.compile(r"^\| (✅ )?`([a-z0-9_]+)`")


def read_dart_registry(path: str) -> list[str]:
    """IDs in declaration order from a `id: '<id>'` Dart registry."""
    with open(path, encoding="utf-8") as f:
        text = f.read()
    return re.findall(r"^\s+id: '([a-z0-9_]+)',$", text, re.MULTILINE)


def read_num_variants(path: str) -> dict[str, int]:
    """{building_id: numVariants} from building_registry.dart (default 0)."""
    with open(path, encoding="utf-8") as f:
        text = f.read()
    out: dict[str, int] = {}
    # Split on BuildingType( so each chunk holds one entry's fields.
    for chunk in text.split("BuildingType(")[1:]:
        m_id = re.search(r"id: '([a-z0-9_]+)'", chunk)
        if not m_id:
            continue
        m_nv = re.search(r"numVariants: (\d+)", chunk)
        out[m_id.group(1)] = int(m_nv.group(1)) if m_nv else 0
    return out


def read_asset_variants() -> dict[str, int]:
    """{building_id: count of processed assets/buildings/<id>_v<n>.png}."""
    if not os.path.isdir(ASSETS_DIR):
        return {}
    out: dict[str, int] = {}
    for fname in os.listdir(ASSETS_DIR):
        m = ASSET_RE.match(fname)
        if m:
            out[m.group(1)] = out.get(m.group(1), 0) + 1
    return out


def toggle_row(line: str, implemented: set[str]):
    m = ROW_RE.match(line)
    if not m:
        return line, None
    is_marked = m.group(1) is not None
    rid = m.group(2)
    should_be_marked = rid in implemented
    if is_marked == should_be_marked:
        return line, ("unchanged", rid)
    if should_be_marked:
        return line.replace(f"| `{rid}`", f"| ✅ `{rid}`", 1), ("added", rid)
    return line.replace(f"| ✅ `{rid}`", f"| `{rid}`", 1), ("removed", rid)


def update_impl_block(text: str, body: str) -> str:
    """Replace the §6 fenced block, or insert it after the §6 heading."""
    new_block = f"{IMPL_BEGIN}\n{body}\n{IMPL_END}"
    if "IMPL_STATUS_BEGIN" in text:
        return re.sub(
            r"<!-- IMPL_STATUS_BEGIN[^>]*-->.*?<!-- IMPL_STATUS_END -->",
            new_block.replace("\\", "\\\\"),
            text,
            count=1,
            flags=re.DOTALL,
        )
    m = re.search(r"^## 6\. Implementation status$", text, re.MULTILINE)
    if not m:
        return text.rstrip() + "\n\n" + new_block + "\n"
    return text[: m.end()] + "\n\n" + new_block + text[m.end() :]


def main() -> int:
    building_ids = set(read_dart_registry(BUILDING_REGISTRY))
    beat_ids = set(read_dart_registry(BEAT_REGISTRY))
    num_variants = read_num_variants(BUILDING_REGISTRY)
    asset_variants = read_asset_variants()
    today = datetime.date.today().isoformat()

    with open(CITY_BUILDER, encoding="utf-8") as f:
        lines = f.readlines()

    # §3.1–§3.4 rows are buildings; §4.x rows are beats. Other sections reuse
    # the same backticked-ID row shape (§3.6 long-tail templates, §5.4 variant
    # counts), so the toggle only runs inside the catalog sections proper.
    added = removed = 0
    section = None  # "buildings" | "beats" | None
    found_buildings: set[str] = set()
    found_beats: set[str] = set()
    n_buildings = n_buildings_done = n_beats = n_beats_done = 0
    out_lines: list[str] = []
    for line in lines:
        stripped = line.strip()
        if stripped.startswith("#"):
            if re.match(r"^### 3\.[1-4] ", stripped):
                section = "buildings"
            elif re.match(r"^### 4\.[1-4] ", stripped):
                section = "beats"
            else:
                section = None
        if section is not None:
            implemented = building_ids if section == "buildings" else beat_ids
            new_line, info = toggle_row(line, implemented)
            if info is not None:
                action, rid = info
                if action == "added":
                    added += 1
                elif action == "removed":
                    removed += 1
                marked = new_line.startswith("| ✅ ")
                if section == "buildings":
                    found_buildings.add(rid)
                    n_buildings += 1
                    n_buildings_done += marked
                else:
                    found_beats.add(rid)
                    n_beats += 1
                    n_beats_done += marked
                out_lines.append(new_line)
                continue
        out_lines.append(line)

    text = "".join(out_lines)

    with_art = sorted(b for b in building_ids if asset_variants.get(b, 0) > 0)
    awaiting_art = sorted(b for b in building_ids if asset_variants.get(b, 0) == 0)
    art_note = (
        f"`{'`, `'.join(awaiting_art)}`" if awaiting_art else "(none)"
    )
    body = (
        f"- **Implementation status (auto-updated {today}):**\n"
        f"  - §3 buildings: **{n_buildings_done} / {n_buildings} wired** — see ✅ marks in §3.1–§3.4. Source of truth: [building_registry.dart](lib/domain/city/building_registry.dart).\n"
        f"  - §4 beats: **{n_beats_done} / {n_beats} wired** — see ✅ marks in §4.x. Source of truth: [beat_registry.dart](lib/domain/city/beat_registry.dart).\n"
        f"  - Sprite art: **{len(with_art)} / {len(building_ids)} wired buildings have processed art** in [assets/buildings/](assets/buildings/). Still on the box placeholder: {art_note}.\n"
        f"  - To refresh these counts and the per-row ✅ marks, run `python3 tools/city_builder/sync_implementation_status.py`."
    )
    text = update_impl_block(text, body)

    with open(CITY_BUILDER, "w", encoding="utf-8") as f:
        f.write(text)

    print(f"buildings: {n_buildings_done} / {n_buildings} wired")
    print(f"beats:     {n_beats_done} / {n_beats} wired")
    print(f"art:       {len(with_art)} / {len(building_ids)} wired buildings have sprites")
    print(f"markers:   +{added} added, -{removed} removed")

    # Audit: registry IDs with no row in the catalog = name drift.
    missing_buildings = building_ids - found_buildings
    if missing_buildings:
        print(
            f"\nWARNING: {len(missing_buildings)} building IDs are in the registry "
            f"but not in city_builder.md §3 (rename/typo?):"
        )
        for rid in sorted(missing_buildings):
            print(f"  - {rid}")
    missing_beats = beat_ids - found_beats
    if missing_beats:
        print(
            f"\nWARNING: {len(missing_beats)} beat IDs are in the registry but "
            f"not in city_builder.md §4 (rename/typo?):"
        )
        for rid in sorted(missing_beats):
            print(f"  - {rid}")

    # Audit: numVariants vs the processed sprites actually on disk.
    for rid in sorted(building_ids):
        declared = num_variants.get(rid, 0)
        on_disk = asset_variants.get(rid, 0)
        if declared != on_disk:
            print(
                f"\nWARNING: {rid}: numVariants={declared} in the registry but "
                f"{on_disk} processed sprite(s) in assets/buildings/"
            )

    # Audit: processed sprites whose ID isn't in the registry at all.
    orphans = sorted(set(asset_variants) - building_ids)
    if orphans:
        print(
            f"\nWARNING: processed sprites exist for IDs not in the registry:"
        )
        for rid in orphans:
            print(f"  - {rid} ({asset_variants[rid]} file(s))")

    return 0


if __name__ == "__main__":
    sys.exit(main())
